name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: docker/setup-buildx-action@v1
      name: Set up Docker Buildx
      id: buildx

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: adfruntime
        tags: 5.9.7984.1
        registry: akavasis.azurecr.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.SECRET_TOKEN_1 }}   
