name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: docker/setup-buildx-action@v1
      name: Set up Docker Buildx
      id: buildx

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: adfruntime
        tags: 5.9.7984.1
        registry: ${{ secrets.ACR }} 
        dockerfile: Dockerfile
        username: ${{ secrets.ACR_TOKEN_ΝΑΜΕ }}
        password: ${{ secrets.ACR_TOKEN_PASSWORD }}   
